name: Build & upload to Firebase App Distribution

on: [push]

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.44.0/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/
      - name: run ktlint
        run: |
          ktlint -F --disabled_rules=no-wildcard-imports --reporter=checkstyle,output=build/ktlint-report.xml
        continue-on-error: true
      - uses: yutailang0119/action-ktlint@v3
        with:
          report-path: build/*.xml
          continue-on-error: true

  build:
    needs: ktlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: build release
        run: ./gradlew assembleRelease

      - name: Get latest merge commit tag
        run: git describe --tags $(git rev-list --tags --max-count=1)
        shell: bash

      - name: Set version environment variable
        run: echo ::set-env name=VERSION::$(git describe --tags $(git rev-list --tags --max-count=1))

      - name: Rename APK file
        run: mv app/build/outputs/apk/release/Animity-v1.1.1-arm64-v8a-release-unsigned.apk app/build/outputs/apk/release/Animity-${{ env.VERSION }}-arm64-v8a-release-unsigned.apk

      - uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: animity-tester
          file: app/build/outputs/apk/release/Animity-${{ env.VERSION }}-arm64-v8a-release-unsigned.apk
